### ISSUE TITLE
Add Build Template to build CRD for V3 API

### ISSUE THREAD

**Issue by ssisil** [buildpack/resources#1]

**Comment by ssisil** [comment]
@sclevine  - team felt there was conflicts with Build CRD and V3 API and want to discuss validity of supporting V3 in build CRD

**Comment by sclevine** [comment]
Anything aside from the need to hard-code the build/run images?

I don't think that will be a huge problem -- it just means that we can't support reduced-size base images on knative (at least initially).

**Comment by jchesterpivotal** [comment]
We've [opened a PR](https://github.com/knative/build-templates/pull/65) against the Build Templates repository.

**Comment by ekcasey** [comment]
updated PR https://github.com/knative/build-templates/pull/67, waiting for comments & merge
